// tests/parity.test.js — Phase DP item 6: faithful-rebuild parity gates.
// Asserts the committed research/parity-summary.json (generated by
// `node scripts/parity.js` against a running server) shows every ported page
// passing: text coverage >= 99.5% (or a documented text exception with word
// recall >= 99%), 0 order inversions, all old images present in order,
// no missing old links/files, layout signature equal. Regenerate the summary
// with scripts/parity.js after changing blocks, routes or templates.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SUMMARY = path.join(ROOT, 'research', 'parity-summary.json');

test('parity summary exists and is fresh enough', () => {
  assert.ok(fs.existsSync(SUMMARY), 'run node scripts/parity.js first (research/parity-summary.json missing)');
  const s = JSON.parse(fs.readFileSync(SUMMARY, 'utf8'));
  assert.ok(s.pages && Object.keys(s.pages).length >= 20, 'parity summary must cover the ported pages');
  const age = Date.now() - new Date(s.generated).getTime();
  assert.ok(age < 14 * 24 * 3600 * 1000, `parity summary is stale (generated ${s.generated}); re-run scripts/parity.js`);
});

test('every ported page passes parity (text/order/images/links/layout)', () => {
  const s = JSON.parse(fs.readFileSync(SUMMARY, 'utf8'));
  const bad = Object.entries(s.pages).filter(([, r]) => r.verdict !== 'PASS');
  assert.deepEqual(
    bad.map(([slug, r]) => `${slug}: ${r.verdict}`),
    [],
    'parity failures — see research/PARITY.md for per-page numbers'
  );
});

test('dp-import manifest matches the pages in the summary', () => {
  const s = JSON.parse(fs.readFileSync(SUMMARY, 'utf8'));
  const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'research', 'dp-import.json'), 'utf8'));
  for (const slug of Object.keys(s.pages)) {
    assert.ok(manifest.pages[slug], `dp-import.json has no entry for ported page ${slug}`);
  }
});
